title = "Zuofei's Blog"
theme = "../../../zuofeihong.github.io"
baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
summarylength = 100
enableEmoji = true
enableRobotsTXT = true
paginate = 10

# Disqus comments
# https://gohugo.io/templates/internal/#configure-disqus
# disqusShortname = ""

# Google Analytics
# https://gohugo.io/templates/internal/#google-analytics
# googleAnalytics = ""

[Languages]
  [Languages.en]
    contentDir = "content"
    weight = 1
    LanguageName = "en"

[params.author]
  name = "Zuofei Hong"
  email = "hzf7725@gmail.com"
[params]
  title = "Zuofei's Blog"
  description = "I share my thoughts on Genetics, programming, and life."
  profilePicture = "/images/zuofei.jpg"
  favicon = "favicons/"
  customCss = []
  customJs = []
  displayMode = "light"
  images = ['/images/zuofei.jpg']

[taxonomies]
  series = 'series'
  author = "authors"

# Sketch settings
# you can also enable or disable it per page
[params.sketch] 
  enable = true
  # Graph, Digital Rain, or Circles
  use = "Graph"
  # JSON that is passed to the sketch constructor
  # You can check all the possible configurations in
  startingConfig = """{
    "kind": "katakana",
    "nStreams": 10
  }"""


## Math settings
[params.math]
  # global support, you can also configure it per page
  enable = true
  # katex or mathjax, default is mathjax
  use = "mathjax"

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin" # Font-awesome icon
title = "Linkedin"
url = "https://www.linkedin.com/in/roopini-ssk/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/zuofeihong"

##[[params.socialIcons]]
##icon = "fab fa-instagram"
##title = "instagram"
##url = "https://www.instagram.com/roopini0121/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:roopinissk@gmail.com"

# Menu items
[menu]
[[Languages.en.menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[Languages.en.menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"

[[Languages.en.menu.main]]
name = "Art"
weight = 300
identifier = "art"
url = "/art/"

[[Languages.en.menu.main]]
name = "About"
weight = 400
identifier = "about"
url = "/about/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 1
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

# Hugo will ignore these files, .rmd and .rmarkdown are taken care by blogdown
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]